name: CFN CI/CD

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'infra/template.yaml'
      - 'infra/params/dev.json'
      - '.github/workflows/deploy-infra.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/template.yaml'
      - 'infra/params/production.json'
      - '.github/workflows/deploy-infra.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Linting CFN template
        run: cfn-lint infra/batch-processing-template.yaml

  deploy-dev:
    needs: validate
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CICD_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy to dev
        run: |
          aws cloudformation deploy \
            --stack-name ad-campaign-dev \
            --template-file infra/template.yaml \
            --parameter-overrides file://infra/params/dev.json \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

  deploy-prod:
    needs: validate
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CICD_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy to production
        run: |
          aws cloudformation deploy \
            --stack-name ad-campaign-prod \
            --template-file infra/template.yaml \
            --parameter-overrides file://infra/params/production.json \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset
